import '../models/readme_element.dart';

class ProjectTemplate {
  final String name;
  final String description;
  final List<ReadmeElement> elements;

  ProjectTemplate({
    required this.name,
    required this.description,
    required this.elements,
  });
}

class Templates {
  static List<ProjectTemplate> get all => [
        ProjectTemplate(
          name: 'Minimal',
          description: 'Basic structure with Project Name, Description, and License.',
          elements: [
            HeadingElement(text: '[PROJECT_NAME]', level: 1),
            BadgeElement(label: 'License', imageUrl: 'https://img.shields.io/badge/license-MIT-blue.svg', targetUrl: ''),
            ParagraphElement(text: 'A brief description of what this project does and who it\'s for.'),
            HeadingElement(text: 'License', level: 2),
            ParagraphElement(text: 'MIT License. Copyright (c) [CURRENT_YEAR] [GITHUB_USERNAME]'),
          ],
        ),
        ProjectTemplate(
          name: 'Library / Package',
          description: 'Includes Installation, Usage, and Example sections.',
          elements: [
            HeadingElement(text: '[PROJECT_NAME]', level: 1),
            BadgeElement(label: 'Version', imageUrl: 'https://img.shields.io/pub/v/[PROJECT_NAME]', targetUrl: 'https://pub.dev/packages/[PROJECT_NAME]'),
            BadgeElement(label: 'License', imageUrl: 'https://img.shields.io/badge/license-MIT-blue.svg', targetUrl: ''),
            BadgeElement(label: 'Build Status', imageUrl: 'https://img.shields.io/github/actions/workflow/status/[GITHUB_USERNAME]/[PROJECT_NAME]/main.yml', targetUrl: ''),
            ParagraphElement(text: 'A powerful library for...'),
            HeadingElement(text: 'Features', level: 2),
            ListElement(items: ['Feature 1', 'Feature 2', 'Feature 3']),
            HeadingElement(text: 'Installation', level: 2),
            CodeBlockElement(code: 'flutter pub add [PROJECT_NAME]', language: 'bash'),
            HeadingElement(text: 'Usage', level: 2),
            CodeBlockElement(code: 'import \'package:[PROJECT_NAME]/[PROJECT_NAME].dart\';\n\nvoid main() {\n  // Use the library\n}', language: 'dart'),
            HeadingElement(text: 'License', level: 2),
            ParagraphElement(text: 'MIT License. Copyright (c) [CURRENT_YEAR] [GITHUB_USERNAME]'),
          ],
        ),
        ProjectTemplate(
          name: 'Full Project',
          description: 'Comprehensive structure including Prerequisites, Contributing, and Tests.',
          elements: [
            HeadingElement(text: '[PROJECT_NAME]', level: 1),
            GitHubStatsElement(repoName: '[GITHUB_USERNAME]/[PROJECT_NAME]', showStars: true, showForks: true, showIssues: true, showLicense: true),
            ParagraphElement(text: 'A complete solution for...'),
            HeadingElement(text: 'Screenshots', level: 2),
            ParagraphElement(text: '![App Screenshot](https://via.placeholder.com/800x400)'),
            HeadingElement(text: 'Features', level: 2),
            ListElement(items: ['Feature A', 'Feature B', 'Feature C']),
            HeadingElement(text: 'Tech Stack', level: 2),
            ListElement(items: ['Flutter', 'Dart', 'Firebase']),
            HeadingElement(text: 'Prerequisites', level: 2),
            ListElement(items: ['Flutter SDK', 'Android Studio / VS Code']),
            HeadingElement(text: 'Installation', level: 2),
            CodeBlockElement(code: 'git clone https://github.com/[GITHUB_USERNAME]/[PROJECT_NAME].git\ncd [PROJECT_NAME]\nflutter pub get', language: 'bash'),
            HeadingElement(text: 'Running Tests', level: 2),
            CodeBlockElement(code: 'flutter test', language: 'bash'),
            HeadingElement(text: 'Contributing', level: 2),
            ParagraphElement(text: 'Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.'),
            HeadingElement(text: 'License', level: 2),
            ParagraphElement(text: 'MIT License. Copyright (c) [CURRENT_YEAR] [GITHUB_USERNAME]'),
          ],
        ),
        ProjectTemplate(
          name: 'Open Source Professional',
          description: 'Top-tier template for serious open source projects.',
          elements: [
            HeadingElement(text: '[PROJECT_NAME]', level: 1),
            ParagraphElement(text: '<div align="center">\n  <img src="assets/logo.png" alt="Logo" width="80" height="80">\n  <h3>[PROJECT_NAME]</h3>\n  <p>Awesome project description goes here.</p>\n</div>'),
            GitHubStatsElement(repoName: '[GITHUB_USERNAME]/[PROJECT_NAME]', showStars: true, showForks: true, showIssues: true, showLicense: true),
            SocialsElement(profiles: [
              SocialProfile(platform: 'discord', username: 'InviteLink'),
              SocialProfile(platform: 'twitter', username: '[GITHUB_USERNAME]'),
            ], style: 'for-the-badge'),
            TOCElement(title: 'Table of Contents'),
            HeadingElement(text: 'About The Project', level: 2),
            ParagraphElement(text: 'Detailed description of the project, its goals, and why it exists.'),
            HeadingElement(text: 'Built With', level: 3),
            ListElement(items: ['Flutter', 'Dart', 'Firebase', 'Node.js']),
            HeadingElement(text: 'Getting Started', level: 2),
            ParagraphElement(text: 'To get a local copy up and running follow these simple steps.'),
            HeadingElement(text: 'Prerequisites', level: 3),
            CodeBlockElement(code: 'npm install npm@latest -g', language: 'bash'),
            HeadingElement(text: 'Installation', level: 3),
            CodeBlockElement(code: 'git clone https://github.com/[GITHUB_USERNAME]/[PROJECT_NAME].git\ncd [PROJECT_NAME]\nnpm install', language: 'bash'),
            HeadingElement(text: 'Usage', level: 2),
            ParagraphElement(text: 'Use this space to show useful examples of how a project can be used. Additional screenshots, code examples and demos work well in this space.'),
            HeadingElement(text: 'Roadmap', level: 2),
            ListElement(items: ['[ ] Feature 1', '[ ] Feature 2', '[x] Feature 3']),
            HeadingElement(text: 'Contributing', level: 2),
            ParagraphElement(text: 'Contributions are what make the open source community such an amazing place to learn, inspire, and create. Any contributions you make are **greatly appreciated**.'),
            HeadingElement(text: 'License', level: 2),
            ParagraphElement(text: 'Distributed under the MIT License. See `LICENSE` for more information.'),
            HeadingElement(text: 'Contact', level: 2),
            SocialsElement(profiles: [
              SocialProfile(platform: 'email', username: 'your_email@example.com'),
              SocialProfile(platform: 'linkedin', username: '[GITHUB_USERNAME]'),
            ], style: 'flat'),
            HeadingElement(text: 'Acknowledgments', level: 2),
            ListElement(items: ['GitHub Emoji Cheat Sheet', 'Img Shields', 'Choose an Open Source License']),
          ],
        ),
        ProjectTemplate(
          name: 'Mobile App',
          description: 'Showcase your mobile application with screenshots and download links.',
          elements: [
            HeadingElement(text: '[PROJECT_NAME]', level: 1),
            ParagraphElement(text: 'A brief description of your mobile application.'),
            BadgeElement(label: 'Platform', imageUrl: 'https://img.shields.io/badge/Platform-Flutter-02569B?logo=flutter', targetUrl: 'https://flutter.dev'),
            HeadingElement(text: 'Screenshots', level: 2),
            ParagraphElement(text: '<div align="center">\n  <img src="path/to/screenshot1.png" width="200" />\n  <img src="path/to/screenshot2.png" width="200" />\n  <img src="path/to/screenshot3.png" width="200" />\n</div>'),
            HeadingElement(text: 'Download', level: 2),
            BadgeElement(label: 'Google Play', imageUrl: 'https://img.shields.io/badge/Google_Play-414141?style=for-the-badge&logo=google-play&logoColor=white', targetUrl: '#'),
            BadgeElement(label: 'App Store', imageUrl: 'https://img.shields.io/badge/App_Store-0D96F6?style=for-the-badge&logo=app-store&logoColor=white', targetUrl: '#'),
            HeadingElement(text: 'Features', level: 2),
            ListElement(items: ['User Authentication', 'Real-time Chat', 'Push Notifications', 'Dark Mode']),
            HeadingElement(text: 'Tech Stack', level: 2),
            ListElement(items: ['Flutter', 'Bloc', 'Firebase']),
            HeadingElement(text: 'Feedback', level: 2),
            ParagraphElement(text: 'If you have any feedback, please reach out to us at support@example.com'),
          ],
        ),
        ProjectTemplate(
          name: 'Backend API',
          description: 'Documentation for backend services and APIs.',
          elements: [
            HeadingElement(text: '[PROJECT_NAME] API', level: 1),
            ParagraphElement(text: 'Documentation for the [PROJECT_NAME] REST API.'),
            BadgeElement(label: 'Status', imageUrl: 'https://img.shields.io/badge/status-active-success.svg', targetUrl: ''),
            HeadingElement(text: 'Base URL', level: 2),
            CodeBlockElement(code: 'https://api.example.com/v1', language: 'plaintext'),
            HeadingElement(text: 'Authentication', level: 2),
            ParagraphElement(text: 'This API uses Bearer Token authentication.'),
            CodeBlockElement(code: 'Authorization: Bearer <YOUR_TOKEN>', language: 'http'),
            HeadingElement(text: 'Endpoints', level: 2),
            HeadingElement(text: 'GET /users', level: 3),
            ParagraphElement(text: 'Returns a list of users.'),
            CodeBlockElement(code: '[\n  {\n    "id": 1,\n    "name": "John Doe"\n  }\n]', language: 'json'),
            HeadingElement(text: 'POST /users', level: 3),
            ParagraphElement(text: 'Creates a new user.'),
            CodeBlockElement(code: '{\n  "name": "Jane Doe",\n  "email": "jane@example.com"\n}', language: 'json'),
            HeadingElement(text: 'Error Handling', level: 2),
            TableElement(headers: ['Code', 'Description'], rows: [['400', 'Bad Request'], ['401', 'Unauthorized'], ['404', 'Not Found'], ['500', 'Server Error']], alignments: [ColumnAlignment.left, ColumnAlignment.left]),
          ],
        ),
        ProjectTemplate(
          name: 'Data Science / ML',
          description: 'For data analysis and machine learning projects.',
          elements: [
            HeadingElement(text: '[PROJECT_NAME]', level: 1),
            ParagraphElement(text: 'Project description and objectives.'),
            BadgeElement(label: 'Python', imageUrl: 'https://img.shields.io/badge/Python-3.8%2B-blue', targetUrl: ''),
            BadgeElement(label: 'License', imageUrl: 'https://img.shields.io/badge/License-MIT-green', targetUrl: ''),
            HeadingElement(text: 'Dataset', level: 2),
            ParagraphElement(text: 'Description of the dataset used, source, and preprocessing steps.'),
            HeadingElement(text: 'Methodology', level: 2),
            ParagraphElement(text: 'Explanation of the algorithms and models used.'),
            HeadingElement(text: 'Results', level: 2),
            ParagraphElement(text: 'Summary of the results, accuracy metrics, and visualizations.'),
            HeadingElement(text: 'Installation', level: 2),
            CodeBlockElement(code: 'pip install -r requirements.txt', language: 'bash'),
            HeadingElement(text: 'Usage', level: 2),
            CodeBlockElement(code: 'python train.py\npython predict.py', language: 'bash'),
            HeadingElement(text: 'Project Structure', level: 2),
            CodeBlockElement(code: '├── data/\n├── models/\n├── notebooks/\n├── src/\n└── README.md', language: 'plaintext'),
          ],
        ),
        ProjectTemplate(
          name: 'Contributing Guide',
          description: 'Standard CONTRIBUTING.md structure.',
          elements: [
            HeadingElement(text: 'Contributing to [PROJECT_NAME]', level: 1),
            ParagraphElement(text: 'First off, thanks for taking the time to contribute! ❤️'),
            HeadingElement(text: 'How to Contribute', level: 2),
            ParagraphElement(text: '1. Fork the repo and create your branch from `main`.\n2. If you\'ve added code that should be tested, add tests.\n3. Ensure the test suite passes.\n4. Make sure your code lints.'),
            HeadingElement(text: 'Pull Request Process', level: 2),
            ListElement(items: ['Update the README.md with details of changes to the interface.', 'Increase the version numbers in any examples files and the README.md to the new version that this Pull Request would represent.']),
          ],
        ),
        ProjectTemplate(
          name: 'Documentation Site',
          description: 'Structure for a documentation-heavy project.',
          elements: [
            HeadingElement(text: '[PROJECT_NAME] Documentation', level: 1),
            ParagraphElement(text: 'Welcome to the official documentation for [PROJECT_NAME].'),
            TOCElement(title: 'Table of Contents'),
            HeadingElement(text: 'Getting Started', level: 2),
            ParagraphElement(text: 'Introduction to the core concepts...'),
            HeadingElement(text: 'API Reference', level: 2),
            ParagraphElement(text: 'Detailed API documentation...'),
            HeadingElement(text: 'Tutorials', level: 2),
            ListElement(items: ['Basic Usage', 'Advanced Configuration', 'Integration Guide']),
            HeadingElement(text: 'FAQ', level: 2),
            CollapsibleElement(summary: 'How do I reset the configuration?', content: 'You can reset by running `reset_config.sh`.'),
          ],
        ),
      ];
}
